/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-9-6 下午2:50' with Gradle 2.8
 *
 * @author Administrator, @date 16-9-6 下午2:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
